# Generated by Django 4.0.5 on 2022-06-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201008_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
