# Generated by Django 4.0.5 on 2022-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_city_alter_notes_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
