# Generated by Django 4.0.5 on 2022-06-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_signup_paym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='paym',
        ),
    ]
