# Generated by Django 4.0.5 on 2022-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_donatefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
