# Generated by Django 4.0.5 on 2022-06-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_signup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='proffession',
        ),
    ]
