# Generated by Django 4.0.5 on 2022-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_remove_signup_branch_remove_signup_proffession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
