# Generated by Django 4.0.5 on 2022-06-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_alter_signup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='image',
        ),
    ]
